name: CI
on: [push]
jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: php-actions/composer@v6
    - name: Run tests
      uses: php-actions/composer@v6
      with:
        command: test
